export const dataUsuarios = [
  {
    nombre: 'jose',
    apellido: 'gonzalez',
    email: 'jose@gmail.com',
    edad: '20',
    direccion: 'santiago',
    courId: '2',
  },
  {
    nombre: 'fernando',
    apellido: 'lopez',
    email: 'fernando@gmail.com',
    edad: '22',
    direccion: 'santiago',
    courId: '3',
  },
  {
    nombre: 'maria',
    apellido: 'sanchez',
    email: 'maria@gmail.com',
    edad: '29',
    direccion: 'santiago',
    courId: '2',
  },
  {
    nombre: 'carlos',
    apellido: 'gonzalez',
    email: 'carlos@gmail.com',
    edad: '26',
    direccion: 'santiago',
    courId: '1',
  },
  {
    nombre: 'gustavo',
    apellido: 'mejia',
    email: 'gustavo@gmail.com',
    edad: '23',
    direccion: 'santiago',
    courId: '1',
  },
];
export const dataCursos = [
  {
    nombre: 'sistemas',
    codigo: '1001',
    year: '2023',
    semestre: '6',
    sede: 'ingenieria',
  },
  {
    nombre: 'informatica',
    codigo: '1002',
    year: '2023',
    semestre: '6',
    sede: 'ingenieria',
  },
  {
    nombre: 'odontologia',
    codigo: '2001',
    year: '2023',
    semestre: '6',
    sede: 'medicina',
  },
  {
    nombre: 'mecanica',
    codigo: '1003',
    year: '2023',
    semestre: '6',
    sede: 'ingenieria',
  },
  {
    nombre: 'enfermeria',
    codigo: '2002',
    year: '2023',
    semestre: '6',
    sede: 'medicina',
  },
  {
    nombre: 'sistemas',
    codigo: '5001',
    year: '2023',
    semestre: '6',
    sede: 'ingenieria',
  },
];
